from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

MODULE_PATH = (
    Path(__file__).resolve().parents[1] / "research" / "v2e_imu" / "autoresearch_runner.py"
)
spec = importlib.util.spec_from_file_location("autoresearch_runner", MODULE_PATH)
assert spec is not None and spec.loader is not None
runner = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = runner
spec.loader.exec_module(runner)


class AutoresearchRunnerTests(unittest.TestCase):
    def test_restore_baseline_uses_best_batch4_defaults(self) -> None:
        restored = runner.restore_baseline(runner.TRAIN_FILE.read_text(encoding="utf-8"))

        self.assertIn("TOTAL_BATCH_SIZE = 4", restored)
        self.assertIn("LEARNING_RATE = 2e-3", restored)
        self.assertIn("WEIGHT_DECAY = 0.0", restored)

    def test_build_training_env_includes_autoresearch_mlflow_tags(self) -> None:
        exp = runner.Experiment(
            name="optuna search",
            description="generated by optuna",
            commit_message="probe: optuna",
            search_strategy="optuna",
            metadata={"trial_number": "7"},
        )

        env = runner.build_training_env(exp, {"EXISTING": "1"})

        self.assertEqual(env["MLFLOW_RUN_NAME"], "optuna search")
        self.assertEqual(env["AUTORESEARCH_SEARCH_KIND"], "optuna")
        self.assertEqual(env["AUTORESEARCH_TRIAL_NUMBER"], "7")
        self.assertEqual(env["AUTORESEARCH_EXPERIMENT_NAME"], "optuna search")

    def test_build_optuna_experiment_returns_trial(self) -> None:
        config = runner.OptunaConfig(
            enabled=True,
            study_name="unit-test-study",
            storage_url="sqlite:///:memory:",
            max_generated=1,
        )

        exp = runner.build_optuna_experiment(config, completed_descriptions=set())

        self.assertIsNotNone(exp)
        assert exp is not None
        self.assertEqual(exp.search_strategy, "optuna")
        self.assertIn("LEARNING_RATE", exp.constants)
        self.assertIn("TOTAL_BATCH_SIZE", exp.constants)

    def test_build_optuna_experiment_advances_between_calls(self) -> None:
        with tempfile.NamedTemporaryFile(suffix=".db") as tmp:
            config = runner.OptunaConfig(
                enabled=True,
                study_name="unit-test-study-advance",
                storage_url=f"sqlite:///{tmp.name}",
                max_generated=1,
                sampler_seed=42,
            )

            first = runner.build_optuna_experiment(config, completed_descriptions=set())
            second = runner.build_optuna_experiment(config, completed_descriptions=set())

        self.assertIsNotNone(first)
        self.assertIsNotNone(second)
        assert first is not None and second is not None
        self.assertNotEqual(first.constants, second.constants)

    def test_build_optuna_experiment_includes_architecture_choices(self) -> None:
        with tempfile.NamedTemporaryFile(suffix=".db") as tmp:
            config = runner.OptunaConfig(
                enabled=True,
                study_name="unit-test-study-architecture",
                storage_url=f"sqlite:///{tmp.name}",
                max_generated=1,
                model_type_choices=("unet", "fno"),
                fusion_type_choices=("film", "gated"),
                model_family_choices=("light", "heavy"),
                unet_depth_choices=(2, 4),
                fno_layer_choices=(2, 6),
                fno_channel_choices=(96, 160),
            )

            exp = runner.build_optuna_experiment(config, completed_descriptions=set())

        self.assertIsNotNone(exp)
        assert exp is not None
        self.assertIn("MODEL_TYPE", exp.constants)
        model_type = exp.constants["MODEL_TYPE"].strip('"')
        self.assertIn(model_type, {"unet", "fno"})
        if model_type == "unet":
            self.assertIn("FUSION_TYPE", exp.constants)
            self.assertIn("MODEL_FAMILY", exp.constants)
            self.assertIn("UNET_DEPTH", exp.constants)
        else:
            self.assertIn("FNO_LAYERS", exp.constants)
            self.assertIn("FNO_CHANNELS", exp.constants)

    def test_compute_autoresearch_score_rewards_better_efficiency(self) -> None:
        fast = runner.RunMetrics(
            val_ap=0.62,
            f1_score=0.58,
            peak_vram_mb=2048.0,
            samples_per_sec=30.0,
            total_seconds=910.0,
        )
        slow = runner.RunMetrics(
            val_ap=0.62,
            f1_score=0.58,
            peak_vram_mb=6144.0,
            samples_per_sec=8.0,
            total_seconds=1010.0,
        )

        self.assertGreater(
            runner.compute_autoresearch_score(fast), runner.compute_autoresearch_score(slow)
        )

    def test_completed_descriptions_treat_crash_as_done(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            results_path = Path(tmpdir) / "results.tsv"
            results_path.write_text(
                "commit\tval_ap\tpeak_memory_gb\tstatus\tdescription\n"
                "abc123\t0.000000\t0.0\tcrash\tManual probe failed\n",
                encoding="utf-8",
            )
            with mock.patch.object(runner, "RESULTS_TSV", results_path):
                completed = runner.completed_experiment_descriptions()

        self.assertIn("Manual probe failed", completed)
        self.assertIn("Manual probe", completed)


if __name__ == "__main__":
    unittest.main()
